<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\DBGuard.Common\DBGuard.Common.csproj" />
      <ProjectReference Include="..\DBGuard.Contracts\DBGuard.Contracts.csproj" />
      <ProjectReference Include="..\DBGuard.DataAccess\DBGuard.DataAccess.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="BCrypt.Net-Next" Version="4.1.0" />
      <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.1" />
      <PackageReference Include="Quartz" Version="3.18.1" />
    </ItemGroup>

</Project>
